### PR TITLE
Fix global timezone set

### LINKED ISSUE #40: DateTime objects use System time zone instead of Luxon's
Not sure if this is intended or not:

```js
Settings.defaultZone = 'Europe/Berlin'
```

```hbs
<PowerCalendar @onSelect={{this.selectCalendarDay}} />
```

```js
@action
async selectCalendarDay(date: {
    datetime: DateTime;
  }): Promise<void> {
    console.log(
      datetime.zoneName,
    );
```

Instead of `'Europe/Berlin'`, the system time zone is logged. This can lead to issues down the line, e.g. when sending this DateTime to and endpoint including the hour and time zone. 

A workaround is to call `.setZone(Settings.defaultZone, { keepLocalTime: true })`, which changes the time zone but not the hour.

### PR DESCRIPTION
**Pull request by mkszepp**
fix #40

After this changes we use the timezone which was set over luxon. for example `Settings.defaultZone = 'UTC';`

### CODE REVIEW

**Comment by mkszepp** [comment]
@langalex this should be fix the error...

**Comment by langalex** [comment]
nice. i'm on vacation for 2 weeks. will try it out after that.

**Comment by langalex** [comment]
@mkszepp can confirm the fix is working 🎉

**Comment by mkszepp** [comment]
@langalex thats good... unfortunately I have not yet found a way to make it work in classic and embroider (for this reason tests do fail). I hope i will find time to fix it, than we can release this change. If you want try to fix it, feel free to do it

**Comment by mkszepp** [comment]
I have asked in Discord the embroider team for our issue and we need to make some setup for embroider in future to avoid non synced settings.
For classic build there is atm no additional setup necessary.

I have extended the ReadMe so that everyone know whats necessary to do [see](https://github.com/cibernox/ember-power-calendar-luxon/pull/42/files#diff-db634806705e8fb137517bce6069ade1f094ba1e56148e44cf7afd0d75e42ceeR35-R58)

necessary configuration for apps with embroider:
```js
const path = require('path');

return require('@embroider/compat').compatBuild(app, Webpack, {
  packagerOptions: {
    webpackConfig: {
      resolve: {
        alias: {
          luxon: path.resolve(__dirname, 'node_modules/luxon/build/node/luxon.js'),
        },
      },
    },
  },
});
```

**Comment by langalex** [comment]
amazing. 🥳

**Comment by mkszepp** [comment]
@langalex can you try to use `"ember-power-calendar-luxon": "git+https://github.com/cibernox/ember-power-calendar-luxon.git#8e315c8e5874174b65e02c3f0612476bf17627f2"` inside your app? This includes all changes this changes (its the dist branch).

let me know if everything works fine, so i will make a release in next days

**Comment by langalex** [comment]
sorry for the late reply. the commit you gave does not seem to exist, but i was able to check out and build master and test with that. works! 🥳

**Comment by mkszepp** [comment]
@langalex sry for my delay... discovered that we didn't released this fix... now its released in `v2.0.0`

**Pull request merged**
